//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProject_DataAccess.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily_Fleet_File_Header
    {
        public Daily_Fleet_File_Header()
        {
            this.Daily_Fleet_File_Details = new HashSet<Daily_Fleet_File_Details>();
        }
    
        public int Header_Id { get; set; }
        public string FileName { get; set; }
        public Nullable<int> AgencyId { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public string User { get; set; }
    
        public virtual ICollection<Daily_Fleet_File_Details> Daily_Fleet_File_Details { get; set; }
    }
}
