//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProject_DataAccess.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily_Fleet_File_Details
    {
        public Daily_Fleet_File_Details()
        {
            this.Error_Notes = new HashSet<Error_Notes>();
        }
    
        public int Detail_Id { get; set; }
        public int Header_Id { get; set; }
        public string Brand { get; set; }
        public string VehicleIdNumber { get; set; }
        public string LicensePlateNumber { get; set; }
        public string LicensePlateState { get; set; }
        public Nullable<int> ManufactureYear { get; set; }
        public string VehicleMake { get; set; }
        public string VehicleModel { get; set; }
        public string VehicleColor { get; set; }
        public string LocationGroup { get; set; }
        public string LocationCode { get; set; }
        public string LocationName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Address3 { get; set; }
        public System.DateTime DateTimeStamp { get; set; }
        public string User { get; set; }
        public Nullable<int> ErrorStatus { get; set; }
    
        public virtual Daily_Fleet_File_Header Daily_Fleet_File_Header { get; set; }
        public virtual ICollection<Error_Notes> Error_Notes { get; set; }
    }
}
