//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProject_DataAccess.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error_Acknowledgement_Header
    {
        public Error_Acknowledgement_Header()
        {
            this.Error_Acknowledgement_Details = new HashSet<Error_Acknowledgement_Details>();
        }
    
        public int Header_Id { get; set; }
        public string File_Name { get; set; }
        public int File_Processing_Attempt { get; set; }
        public System.DateTime Date_Time_Stamp { get; set; }
        public string User { get; set; }
    
        public virtual ICollection<Error_Acknowledgement_Details> Error_Acknowledgement_Details { get; set; }
    }
}
