//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProject_DataAccess.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error_Status
    {
        public int ErrorStatus_Id { get; set; }
        public string Error_Details { get; set; }
    }
}
