//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProject_DataAccess.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error_Notes
    {
        public int NoteId { get; set; }
        public string Note { get; set; }
        public System.DateTime NoteDate { get; set; }
        public Nullable<int> FleetDetailId { get; set; }
        public Nullable<int> VechileDetailId { get; set; }
        public string User { get; set; }
    
        public virtual Daily_Fleet_File_Details Daily_Fleet_File_Details { get; set; }
        public virtual Vehicle_Upload_File_Details Vehicle_Upload_File_Details { get; set; }
    }
}
