//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProject_DataAccess.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_Upload_File_Header
    {
        public Vehicle_Upload_File_Header()
        {
            this.Vehicle_Upload_File_Details = new HashSet<Vehicle_Upload_File_Details>();
        }
    
        public int Header_Id { get; set; }
        public string File_Name { get; set; }
        public int Account_Id { get; set; }
        public System.DateTime File_Date { get; set; }
        public System.DateTime Date_Time_Stamp { get; set; }
        public string User { get; set; }
    
        public virtual ICollection<Vehicle_Upload_File_Details> Vehicle_Upload_File_Details { get; set; }
    }
}
