//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleProject_DataAccess.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_Upload_File_Details
    {
        public Vehicle_Upload_File_Details()
        {
            this.Error_Notes = new HashSet<Error_Notes>();
        }
    
        public int Detail_Id { get; set; }
        public Nullable<int> Error_Ack_Detail_Id { get; set; }
        public int Header_Id { get; set; }
        public string License_Plate_Number { get; set; }
        public string License_Plate_State { get; set; }
        public string EZTag_Id { get; set; }
        public string Action_Required { get; set; }
        public string Processing_Status { get; set; }
        public System.DateTime Effective_Date { get; set; }
        public System.DateTime Date_Time_Stamp { get; set; }
        public string User { get; set; }
        public string VehicleIdNumber { get; set; }
    
        public virtual Error_Acknowledgement_Details Error_Acknowledgement_Details { get; set; }
        public virtual ICollection<Error_Notes> Error_Notes { get; set; }
        public virtual Vehicle_Upload_File_Header Vehicle_Upload_File_Header { get; set; }
    }
}
